# This is a basic workflow to help you get started with Actions

name: Build Image

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  create:
    tags:
      - v*


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 0

    - name: Get tag version
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      id: get_tag

    - name: Create images
      run: |
         docker build --build-arg ACCESS_TOKEN_USR=$GITHUB_ACTOR --build-arg ACCESS_TOKEN_PWD=${{ secrets.MY_PAT }} -t docker.pkg.github.com/$GITHUB_REPOSITORY/${REPOSITORY_NAME}:latest .
         docker tag docker.pkg.github.com/$GITHUB_REPOSITORY/${REPOSITORY_NAME}:latest docker.pkg.github.com/$GITHUB_REPOSITORY/${REPOSITORY_NAME}:${{ steps.get_tag.outputs.tag }}
         docker login docker.pkg.github.com -u $GITHUB_ACTOR -p ${{ secrets.MY_PAT }}
         docker push docker.pkg.github.com/${GITHUB_REPOSITORY}/${REPOSITORY_NAME}:latest
         docker push docker.pkg.github.com/${GITHUB_REPOSITORY}/${REPOSITORY_NAME}:${{ steps.get_tag.outputs.tag }}